[manifest]
version = "0.0.9"
priority = 0
dump_lua = true

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/game_object.lua"]'''
pattern = '''
elseif desc_nodes ~= full_UI_table.main and not desc_nodes.name and self.set ~= 'Enhanced' then
    desc_nodes.name = localize{type = 'name_text', key = res.name_key or target.key, set = target.set }
'''
position = "after"
payload = '''
desc_nodes.name = Multiverse.parse_vars(desc_nodes.name, target.vars)
'''
match_indent = true
