[manifest]
version = "0.0.8"
priority = 0

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''
{n=G.UIT.R, config={align = "cm", id = 'row_round'}, nodes={
    {n=G.UIT.C, config={align = "cm"}, nodes=contents.buttons},
    {n=G.UIT.C, config={align = "cm"}, nodes=contents.round}
}},
'''
position = "after"
payload = '''
{n=G.UIT.R, config={align = "cm", id = "row_thaumaturgy"}, nodes = {
    {n=G.UIT.C, config={align = "cm", padding = 0.05, minw = 1.45, minh = 0.55, colour = temp_col, emboss = 0.05, r = 0.1, detailed_tooltip = {set = "Other", key = "mul_thaumaturgy_desc"}}, nodes={
        {n=G.UIT.R, config={align = "cm", padding = 0.05}, nodes={
            {n=G.UIT.T, config={text = localize('k_mul_thaumaturgy_energy') .. ":", minh = 0.33, scale = 0.85*scale, colour = G.C.UI.TEXT_LIGHT, shadow = true}},
            {n=G.UIT.C, config={minw = 0.05}},
            {n=G.UIT.C, config={align = "cm", r = 0.1, minw = 1.2, colour = temp_col2, id = 'col_thaumaturgy_text'}, nodes={
                {n=G.UIT.O, config={object = DynaText({string = {{ref_table = G.GAME, ref_value = 'mul_thaumaturgy_energy'}}, colours = {Multiverse.TRANSMUTED_GRADIENT},shadow = true, scale = 1.4*scale}),id = 'thaumaturgy_UI_count'}},
            }},
        }},
    }},
}},
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''
blind_chips = self.HUD_blind:get_UIE_by_ID('HUD_blind_count'),
'''
position = "after"
payload = '''
mul_thaumaturgy_energy = self.HUD:get_UIE_by_ID("thaumaturgy_UI_count"),
'''
match_indent = true
times = 1